### ISSUE TITLE
Como testar o Código HTML ?

### ISSUE THREAD

**Issue by arixcarvalho** [ifpb-sr/sisriso#13]

**Comment by MariaAdrielly2001** [comment]
Nós também temos essa duvidas !!!

**Comment by alefemoreira** [comment]
# instalar o pipenv e entrar
> pipenv install

> pipenv shell

# adicionar rota no app.py

![image](https://user-images.githubusercontent.com/43935776/63511279-275d5c80-c4b7-11e9-85eb-83ad18f3ccf7.png)

# salvar o HTML na pasta templates em uma pasta com o nome da página

![image](https://user-images.githubusercontent.com/43935776/63511489-bcf8ec00-c4b7-11e9-941f-8d0ce71c1abe.png)

# execute o app.py
> vc precisa estar na pasta sisriso

> flask run -p 8080

![image](https://user-images.githubusercontent.com/43935776/63511588-f598c580-c4b7-11e9-8cb9-e01015e93fe2.png)

**Comment by alefemoreira** [comment]
Se a duvida estiver respondida pode fecha-la

**Comment by edusantana** [comment]
@arixcarvalho se sua dúvida foi sanada você deve fechar o issue, clicando abaixo no botão **Close**.
