### ISSUE TITLE
Implementar melhorias no Template Base

### ISSUE THREAD

**Issue by ismaalves** [ifpb-sr/sisriso#19]
William deverá terminar a base para podermos padronizar os templates

**Comment by edusantana** [comment]
@ismaalves e @Williais recomendo que definam os nomes dos blocos em português. Fica mais fácil para todos entenderem, em vez de:

https://github.com/ifpb-sr/sisriso/blob/fc043f8b53b044ab4d9779bcbfacf4e433368d91/templates/base.html#L49

Usar algo parecido com:

```html
    {% block conteudo_da_pagina %}{% endblock %} 
```
