### ISSUE TITLE
Atualizar o README com informações pertinentes

### ISSUE THREAD

**Issue by edusantana** [ifpb-sr/sisriso#23]
Atualizem o readme de vocês com [informações pertinentes](http://pichiliani.com.br/como-fazer-um-bom-readme-para-o-seu-github/):

- funcionalidades
- como instalar
- como executar
- como testar as funcionalidades

Essas instruções servirão para toda a equipe de desenvolvimento.

**Comment by edusantana** [comment]
Visualmente esta seção não ficou legal:

![readme](https://user-images.githubusercontent.com/3603111/64074104-88d2b780-cc7d-11e9-943c-598b1f39733b.png)

Da forma como está escrita tanto o texto como o código estão com formatação de código. O ideal é que apenas o código seja apresentado com formatação de código.

Recomendo ver [isso https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) e melhorar.

**Comment by edusantana** [comment]
Conteúdo de #13 deveria está no readme.

**Comment by alefemoreira** [comment]
Fiz algumas mudanças, ainda não sei descrever funcionalidades
