### ISSUE TITLE
Como utilizar o template base?

### ISSUE THREAD

**Issue by jessilari** [ifpb-sr/sisriso#24]

**Comment by ismaalves** [comment]
Tutorial do Jinja2:
https://codeburst.io/jinja-2-explained-in-5-minutes-88548486834e

**Comment by edusantana** [comment]
O template base deste projeto encontra-se no arquivo [templates/base.html](https://github.com/ifpb-sr/sisriso/blob/master/templates/base.html).

Perceba quais os blocos são definidos no arquivo, procure por 
`{% block nome-do-bloco %} conteúdo do bloco {% endblock %}`.

Quando o bloco estiver vazio, significa que ele pode ser preenchido nos demais templates, em especial essa linnha:

https://github.com/ifpb-sr/sisriso/blob/fc043f8b53b044ab4d9779bcbfacf4e433368d91/templates/base.html#L49

Nesse template foi criado um bloco com o nome `page_content`. Dentro das outras páginas você deve fornecer o conteúdo de bloco, como feito nesse outro arquivo:

https://github.com/ifpb-sr/sisriso/blob/fc043f8b53b044ab4d9779bcbfacf4e433368d91/templates/secretaria/cadastroSecretaria.html#L6-L124
