### ISSUE TITLE
arquivo .env.exemplo

### ISSUE THREAD

**Issue by alefemoreira** [ifpb-sr/sisriso#27]
O arquivo .env.exemplo serve para colocar apenas as variáveis de ambientes, mas sem os valores? Se tiver que colocar os valores, eu devo commita-lo?

**Comment by edusantana** [comment]
O arquivo `.env.exemplo` deve conter valores que possam ser utilizados para auxiliar o desenvolvimento. A aplicação utilizaria o conteúdo de `.env`. Perceba que [o arquivo .env](https://github.com/ifpb-sr/sisriso/blob/4b87c9deef0e63b0941270092402338b4cc93963/.gitignore#L86) está sendo ignorado.

O arquivo .env.exemplo responde aos seguintes questionamentos:

- Quais as variáveis de ambiente precisam ser configuradas?
- Quais valores posso colocar apenas para executar no desenvolvimento?
- Quais exemplos de valores para as variáveis?
- Como configuro as variáveis de ambiente?

Dessa forma, sempre que vocês utilizarem uma nova variável de ambiente deverão adicionar ao arquivo também, para que as pessoas saibam as respontas às perguntas acima.

Mas para execução, o que será importante é o conteúdo do arquivo `.env`. Tomando o seu projeto anterior, você poderia ter criado esse arquivo e configurar a variavel de ambiente EMAIL e PASSWORD com um valor de exemplo. Então quando alguém baixa o projeto, ler as instruções do README sabe que precisará criar um novo arquiv ` .env` tomando o anterior como exemplo e realizando os ajustes necessários.

**Comment by alefemoreira** [comment]
Duvida sanada

**Comment by edusantana** [comment]
Para editar esses arquivos no cloud9 é necessário configurar para exibir arquivos ocultos.

**Comment by edusantana** [comment]
Para editar esses arquivos no cloud9 é necessário configurar para exibir arquivos ocultos.
