### ISSUE TITLE
Cadastro dos Clientes

### ISSUE THREAD

**Issue by Jamilly2002** [ifpb-sr/sisriso#29]

**Comment by Jamilly2002** [comment]
Não teve atividade como assim ?

Em ter, 17 de set de 2019 21:25, stale[bot] <notifications@github.com>
escreveu:

**Comment by edusantana** [comment]
Oi @Jamilly2002 perceba que o robô informou que não houve atividades **recentemente**.

Devemos manter registrado nos issues todas a atividades que estamos realizado sobre ele.

No futuro procure:

- descrever melhor os issues (esse tem apenas um título e mais nada).
- quando for alterar algum arquivo, utilize o número do issue no commit.
- Referencie no issue o número da estória a que ele se refere.
- Adicione comentários sobre o progresso do issue.
- Registre no issue tudo o que for relevante para sua execução.

**Comment by edusantana** [comment]
@Jamilly2002 verifique este issue https://github.com/ifpb-sr/zagua/issues/40 e tente compreender as minhas palavras aí acima.
