### ISSUE TITLE
Como colocar o código no github?

### ISSUE THREAD

**Issue by arixcarvalho** [ifpb-sr/sisriso#32]
Estamos trabalhando no #31 e não sabemos como enviar.

**Comment by edusantana** [comment]
@arixcarvalho acho sua dúvida pode ser quebrada em duas partes:

1. [Como submeter arquivos ao github](https://www.youtube.com/results?search_query=Como+submeter+arquivos+ao+github)?

2. Aonde salvar o arquivo? com que nome?

Você está no frontend, então acho que salvará os arquivos na pasta [templates](https://github.com/ifpb-sr/sisriso/tree/master/templates).

O nome do arquivo você deve ser acordado com o backend do seu time. Mas você pode colocar qualquer nome... e depois eles renomeiam se for necessário. o mais importante é o arquivo está enviado.
