### ISSUE TITLE
CPF pode ser usado como chave primaria(PK) de Paciente??

### ISSUE THREAD

**Issue by alefemoreira** [ifpb-sr/sisriso#33]
Estou em duvida se o CPF pode ser uma PK de paciente ou se devo criar um ID

**Comment by alefemoreira** [comment]
CPF deve ser unique?

**Comment by edusantana** [comment]
A chave primária deve ser um ID.

Não recomendo colocar o CPF como unique, pq então você estará tornando o CPF obrigatório. Os campos uniques não podem ser null (pois existiriam mais de um null, e não seriam mais unique).

O que você pode fazer, caso utilize o campo CPF em consultas, é adicionar um índice com o CPF, mas somente se existirem consultas pelo CPF.

**Comment by alefemoreira** [comment]
Entendi
