### ISSUE TITLE
TERMINAL E ARQUIVO !!

### ISSUE THREAD

**Issue by VictorVasconcelos2001** [ifpb-sr/sisriso#59]
não estou conseguindo baixar o arquivo do site no github está dizendo que o arquivo não existe!

**Comment by VictorVasconcelos2001** [comment]
O link está a seguir! 
git clone https://github.com/ifpb-sr/sisriso.git

**Comment by edusantana** [comment]
Dúvida resolvida?

**Comment by VictorVasconcelos2001** [comment]
não!!

**Comment by VictorVasconcelos2001** [comment]
consegui, mas a versão do Python esta incompatível com a versão do pipenv

**Comment by edusantana** [comment]
Use o AWS Console
